### ISSUE TITLE
多重選擇即廢票

### ISSUE THREAD

**Issue by mousems** [Neson/NTUvote-UI#1]
Neson:

請幫我加上：在CSS選擇投票類型的時候，後面加上一個值（choseone）之類的，這樣子若使用者選擇兩個以上的候選人（蓋章），在按送出的時候會變成「您選擇多個候選人，將會變成廢票，是否送出？」

**Comment by zetavg** [comment]
加個 HTML class 開啟這個功能嗎？好的。
