### ISSUE TITLE
紅色向右滑的指示 改善

### ISSUE THREAD

**Issue by mousems** [Neson/NTUvote-UI#4]
候選人只有一組或是兩組的時候，介面無法拉動，而向右滑的指示會停留在原地，因為無法滑動，所以也無法讓指標消失，而指標會檔到人頭圖案

看是（？）：
1.如果能判斷需要滑動，再顯示箭頭
2.不能判斷介面需要滑動，就看投了任何一個人之類的把他關掉XD

**Comment by zetavg** [comment]
其實當初設計上是讓這個提示在需要的時候手動加入，文字也可以對其他部分做額外說明之類的...
但確實就造成這個 issue XD

我做 1. 好了，就目前功能上感覺起來比較合理。
